### ISSUE TITLE
Allow wildcards in filepaths

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/changelogged#82]
To enable something like this:

```yaml
changelogs:
  - changelog: ChangeLog.md
    ignore_files:
      - *.md

    version_files:
      - path: */package.yaml
        version_pattern: "version:"

  - changelog: API_ChangeLog.md

    watch_files:
      - **/swagger.json

    version_files:
      - path: **/swagger.json
        version_pattern: '"version":'
```
